const ordinaryDrink = 'Ordinary Drink';
const grandMarnier = 'Grand Marnier';
const shotGlass = 'Shot glass';
const baileysCream = 'Baileys irish cream';

const mockMealById = {
  meals: [
    {
      idMeal: '52977',
      strMeal: 'Corba',
      strDrinkAlternate: null,
      // strCategory: 'Side',
      strArea: 'Turkish',
      strInstructions: 'Pick through your lentils for any foreign debris, rinse them 2 or 3 times, drain, and set aside.  Fair warning, this will probably turn your lentils into a solid block that you’ll have to break up later\r\nIn a large pot over medium-high heat, sauté the olive oil and the onion with a pinch of salt for about 3 minutes, then add the carrots and cook for another 3 minutes.\r\nAdd the tomato paste and stir it around for around 1 minute. Now add the cumin, paprika, mint, thyme, black pepper, and red pepper as quickly as you can and stir for 10 seconds to bloom the spices. Congratulate yourself on how amazing your house now smells.\r\nImmediately add the lentils, water, broth, and salt. Bring the soup to a (gentle) boil.\r\nAfter it has come to a boil, reduce heat to medium-low, cover the pot halfway, and cook for 15-20 minutes or until the lentils have fallen apart and the carrots are completely cooked.\r\nAfter the soup has cooked and the lentils are tender, blend the soup either in a blender or simply use a hand blender to reach the consistency you desire. Taste for seasoning and add more salt if necessary.\r\nServe with crushed-up crackers, torn up bread, or something else to add some extra thickness.  You could also use a traditional thickener (like cornstarch or flour), but I prefer to add crackers for some texture and saltiness.  Makes great leftovers, stays good in the fridge for about a week.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
      strTags: 'Soup',
      strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
      strIngredient1: 'Lentils',
      strIngredient2: 'Onion',
      strIngredient3: 'Carrots',
      strIngredient4: 'Tomato Puree',
      strIngredient5: 'Cumin',
      strIngredient6: 'Paprika',
      strIngredient7: 'Mint',
      strIngredient8: 'Thyme',
      strIngredient9: 'Black Pepper',
      strIngredient10: 'Red Pepper Flakes',
      strIngredient11: 'Vegetable Stock',
      strIngredient12: 'Water',
      strIngredient13: 'Sea Salt',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 cup ',
      strMeasure2: '1 large',
      strMeasure3: '1 large',
      strMeasure4: '1 tbs',
      strMeasure5: '2 tsp',
      strMeasure6: '1 tsp ',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1/2 tsp',
      strMeasure9: '1/4 tsp',
      strMeasure10: '1/4 tsp',
      strMeasure11: '4 cups ',
      strMeasure12: '1 cup ',
      strMeasure13: 'Pinch',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

const mockMealsRecomendations = {
  drinks: [
    {
      idDrink: '15997',
      strDrink: 'GG',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Optional alcohol',
      strGlass: 'Collins Glass',
      strInstructions: 'Pour the Galliano liqueur over ice. Fill the remainder of the glass with ginger ale and thats all there is to it. You now have a your very own GG.',
      strInstructionsES: null,
      strInstructionsDE: 'Den Galliano-Likör über Eis gießen. Füllen Sie den Rest des Glases mit Ginger Ale und das ist alles, was dazu gehört. Du hast jetzt ein eigenes GG.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare il liquore Galliano su ghiaccio.\r\nRiempi il resto del bicchiere con ginger ale e questo è tutto.\r\nOra hai il tuo GG personale.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
      strIngredient1: 'Galliano',
      strIngredient2: 'Ginger ale',
      strIngredient3: 'Ice',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 1/2 shots ',
      strMeasure2: null,
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-18 22:06:00',
    },
    {
      idDrink: '17222',
      strDrink: 'A1',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.',
      strInstructionsES: 'Vierta todos los ingredientes en una coctelera, mezcle y sirva con hielo en un vaso frío.',
      strInstructionsDE: 'Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
      strIngredient1: 'Gin',
      strIngredient2: grandMarnier,
      strIngredient3: 'Lemon Juice',
      strIngredient4: 'Grenadine',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 3/4 shot ',
      strMeasure2: '1 Shot ',
      strMeasure3: '1/4 Shot',
      strMeasure4: '1/8 Shot',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 21:42:09',
    },
    {
      idDrink: '13501',
      strDrink: 'ABC',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'Layered in a shot glass.',
      strInstructionsES: 'Coloque todos los ingredientes en un vaso de chupito.',
      strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l\'Amaretto, 1/3 di Baileys e il restante di Cognac.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
      strIngredient1: 'Amaretto',
      strIngredient2: baileysCream,
      strIngredient3: 'Cognac',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 ',
      strMeasure2: '1/3 ',
      strMeasure3: '1/3 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:32:08',
    },
    {
      idDrink: '17203',
      strDrink: 'Kir',
      strDrinkAlternate: null,
      strTags: 'IBA,ContemporaryClassic',
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Wine Glass',
      strInstructions: 'Add the crème de cassis to the bottom of the glass, then top up with wine.',
      strInstructionsES: null,
      strInstructionsDE: 'Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.',
      strInstructionsFR: null,
      strInstructionsIT: 'Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg',
      strIngredient1: 'Creme de Cassis',
      strIngredient2: 'Champagne',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 part ',
      strMeasure2: '5 parts ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 17:38:14',
    },
    {
      idDrink: '14229',
      strDrink: '747',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'pour kaluha, then Baileys, then Frangelico not chilled and not layered -- SERVE!!!',
      strInstructionsES: null,
      strInstructionsDE: 'Gießen Sie kaluha, dann Baileys, dann Frangelico nicht gekühlt und nicht geschichtet -- SERVE!!!!!!!!',
      strInstructionsFR: null,
      strInstructionsIT: 'Versa Kahlua, Baileys e poi Frangelico.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg',
      strIngredient1: 'Kahlua',
      strIngredient2: baileysCream,
      strIngredient3: 'Frangelico',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 part ',
      strMeasure2: '1/3 part ',
      strMeasure3: '1/3 part ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:28:26',
    },
    {
      idDrink: '15288',
      strDrink: '252',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'Add both ingredients to shot glass, shoot, and get drunk quick',
      strInstructionsES: null,
      strInstructionsDE: 'Beide Zutaten in ein Schnapsglas geben.',
      strInstructionsFR: null,
      strInstructionsIT: 'Aggiungi entrambi gli ingredienti al bicchierino, bevi e ubriacati velocemente',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg',
      strIngredient1: '151 proof rum',
      strIngredient2: 'Wild Turkey',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/2 shot Bacardi ',
      strMeasure2: '1/2 shot ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-18 22:32:42',
    },
    {
      idDrink: '17225',
      strDrink: 'Ace',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Martini Glass',
      strInstructions: 'Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.',
      strInstructionsES: 'Agite todos los ingredientes en una coctelera con hielo y entonces cuélelos sobre un vaso enfriado.',
      strInstructionsDE: 'Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Grenadine',
      strIngredient3: 'Heavy cream',
      strIngredient4: 'Milk',
      strIngredient5: 'Egg White',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 shots ',
      strMeasure2: '1/2 shot ',
      strMeasure3: '1/2 shot ',
      strMeasure4: '1/2 shot',
      strMeasure5: '1/2 Fresh',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 22:05:06',
    },
    {
      idDrink: '17837',
      strDrink: 'Adam',
      strDrinkAlternate: null,
      strTags: 'Alcoholic,Holiday',
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
      strInstructionsES: 'Mezclar todos los ingredientes en una coctelera con cubitos de hielo hasta la mitad. Agitar bien. Colar el contenido en un vaso de cóctel.',
      strInstructionsDE: 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
      strIngredient1: 'Dark rum',
      strIngredient2: 'Lemon juice',
      strIngredient3: 'Grenadine',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1 tsp ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-09-02 11:29:29',
    },
    {
      idDrink: '13332',
      strDrink: 'B-53',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Collins Glass',
      strInstructions: 'Layer the Kahlua, Sambucca and Grand Marnier into a shot glas in that order. Better than B-52',
      strInstructionsES: null,
      strInstructionsDE: 'Schichte die Kahlua, Sambucca und Grand Marnier in dieser Reihenfolge in ein Schnapsglas ein. Besser als B-52',
      strInstructionsFR: null,
      strInstructionsIT: 'Metti Kahlua, Sambuca e Grand Marnier in un bicchierino in quest\'ordine. ',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rwqxrv1461866023.jpg',
      strIngredient1: 'Kahlua',
      strIngredient2: 'Sambuca',
      strIngredient3: grandMarnier,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 shot ',
      strMeasure2: '1/3 shot ',
      strMeasure3: '1/3 shot ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-04-28 18:53:43',
    },
    {
      idDrink: '13938',
      strDrink: 'AT&T',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball Glass',
      strInstructions: 'Pour Vodka and Gin over ice, add Tonic and Stir',
      strInstructionsES: 'Vierta el vodka y la ginebra sobre el hielo, agregue la tónica y revuelva.',
      strInstructionsDE: 'Wodka und Gin über das Eis gießen, Tonic hinzufügen und umrühren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare la vodka e il gin sul ghiaccio, aggiungere l\'acqua tonica e mescolare',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg',
      strIngredient1: 'Absolut Vodka',
      strIngredient2: 'Gin',
      strIngredient3: 'Tonic water',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '4 oz ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-04-24 22:00:19',
    },
    {
      idDrink: '14610',
      strDrink: 'ACID',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.',
      strInstructionsES: 'Vierta primero el Bacardi 151, seguido del Wild Turkey 101 y sirva con Coca-Cola o Dr Pepper.',
      strInstructionsDE: 'Gering den 151 gefolgt von der 101, die mit einer Cola oder Dr. Pepper Chaser serviert wird.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versa prima il Bacardi 151 seguito dal 101, servito con una Coca-Cola.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg',
      strIngredient1: '151 proof rum',
      strIngredient2: 'Wild Turkey',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz Bacardi ',
      strMeasure2: '1 oz ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-11-15 11:28:37',
    },
    {
      idDrink: '15853',
      strDrink: 'B-52',
      strDrinkAlternate: null,
      strTags: 'IBA,NewEra',
      strVideo: null,
      strCategory: 'Shot',
      strIBA: 'New Era Drinks',
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'Layer ingredients into a shot glass. Serve with a stirrer.',
      strInstructionsES: null,
      strInstructionsDE: 'Zutaten in ein Schnapsglas schichten. Mit einem Rührstab servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Metti gli ingredienti in un bicchiere da shot a strati.\r\nServire con una paletta.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/5a3vg61504372070.jpg',
      strIngredient1: baileysCream,
      strIngredient2: grandMarnier,
      strIngredient3: 'Kahlua',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 ',
      strMeasure2: '1/3 ',
      strMeasure3: '1/4 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 18:07:51',
    },
  ],
};

export { mockMealById, mockMealsRecomendations };
